services:
    php:
        container_name: '${DOCKER_PREFIX_NAME}-php'
        build:
            context: ./compose/8.2
            dockerfile: Dockerfile
            args:
                - 'UID=${UID:-1000}'
                - 'GID=${GID:-1000}'
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - "${DOCKER_PHP_PORT:-9000}:9000"
        volumes:
            - './src:/var/www/html'
        networks:
            - local
    nginx:
        container_name: '${DOCKER_PREFIX_NAME}-nginx'
        build:
            context: ./compose/nginx
            dockerfile: Dockerfile
            args:
                - 'UID=${UID:-1000}'
                - 'GID=${GID:-1000}'
        ports:
            - "${DOCKER_NGINX_PORT:-80}:80"
        volumes:
            - './src:/var/www/html'
        depends_on:
            - php
            - mysql
        networks:
            - local
    mysql:
        container_name: '${DOCKER_PREFIX_NAME}-mysql'
        image: mysql:8.0.34
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "${DOCKER_MYSQL_PORT:-3306}:3306"
        volumes:
            - 'mysql-data:/var/lib/mysql'
            - './compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
        networks:
            - local
    mailhog:
        container_name: '${DOCKER_PREFIX_NAME}-mailhog'
        image: 'mailhog/mailhog:latest'
        ports:
            - "${DOCKER_MAILHOG_PORT:-1025}:1025"
            - "${DOCKER_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - local
    composer:
        container_name: '${DOCKER_PREFIX_NAME}-composer'
        image: composer:latest
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php
        networks:
            - local
    artisan:
        container_name: '${DOCKER_PREFIX_NAME}-artisan'
        build:
            context: ./compose/8.2
            dockerfile: Dockerfile
            args:
                - 'UID=${UID:-1000}'
                - 'GID=${GID:-1000}'
        entrypoint: [ '/var/www/html/artisan' ]
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        networks:
            - local

volumes:
    mysql-data:
        driver: local

networks:
    local:
        driver: bridge
